import color

season_1_cities = {
    color.red: [
        'Beijing',
        'Seoul',
        'Shanghai',
        'Hong Kong',
        'Tokyo',
        'Osaka',
        'Taipei',
        'Bangkok',
        'Ho Chi Minh City',
        'Jakarta',
        'Manila',
        'Sydney',
    ],
    color.blue: [
        'San Francisco',
        'Chicago',
        'Montreal',
        'New York',
        'Atlanta',
        'Washington',
        'Madrid',
        'London',
        'Paris',
        'Essen',
        'Milan',
        'St. Petersburg',
    ],
    color.yellow: [
        'Los Angeles',
        'Mexico City',
        'Miami',
        'Bogota',
        'Lima',
        'Sao Paulo',
        'Buenos Aires',
        'Santiago',
        'Lagos',
        'Kinshasa',
        'Khartoum',
        'Johannesburg',
    ],
    color.black: [
        'Algiers',
        'Cairo',
        'Baghdad',
        'Istanbul',
        'Moscow',
        'Tehran',
        'Delhi',
        'Kolkata',
        'Chennai',
        'Mumbai',
        'Karachi',
        'Riyadh',
    ]
}
