# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(choices=[(1, 'Season 1'), (2, 'Season 2')])),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('win', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Campaign')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.AddField(
            model_name='city',
            name='is_faded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='color',
            field=models.CharField(choices=[('r', 'Red'), ('u', 'Blue'), ('y', 'Yellow'), ('b', 'Black')], max_length=1),
        ),
    ]
