# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171021_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='campaign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Campaign'),
        ),
    ]
