# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171114_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='color',
            field=models.CharField(choices=[(b'r', b'Red'), (b'u', b'Blue'), (b'b', b'Black'), (b'y', b'Yellow')], max_length=1),
        ),
    ]
